# Generated by Django 3.0.4 on 2020-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200413_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='author',
            new_name='document_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to='polls/list/'),
        ),
    ]
